theme = "catppuccin_frappe"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
completion-trigger-len = 1
bufferline = "multiple"
idle-timeout = 0
auto-format = true
rulers = [80]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "diagnostics"]
right = ["total-line-numbers", "primary-selection-length", "position"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false
parents = false

[editor.whitespace.render]
space = "none"
tab = "none"
newline = "all"

[editor.whitespace.characters]
newline = "␤"

[editor.indent-guides]
render = false
character = "▏"
skip-levels = 1

[editor.lsp]
display-messages = true
auto-signature-help = true
display-signature-help-docs = true

[keys.normal]
',' = { w = ":w", q = ":q", f = ":fmt", c = ":bc", n = ":new" }
C-h = "move_prev_word_end"
C-l = "move_next_word_start"
"tab" = ":buffer-next"
S-tab = ":buffer-previous"

[keys.insert]
j = { k = "normal_mode" }
C-left = "move_prev_word_start"
C-right = "move_next_word_end"
