theme = "gruvbox"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor]
popup-border = "none"
line-number = "relative"
color-modes = true
completion-trigger-len = 1
bufferline = "always"
idle-timeout = 0
auto-format = true
rulers = [80]

[editor.statusline]
left = [
  "mode",
  "spinner",
  "spacer",
  "version-control",
  "workspace-diagnostics",
  "spacer",
]
# center = ["file-modification-indicator", "file-name", "diagnostics"]
center = ["diagnostics", "file-name"]
right = [
  "total-line-numbers",
  "primary-selection-length",
  "position",
  "position-percentage",
  "spacer",
]

[editor.statusline.mode]
normal = "NOR"
insert = "INS"
select = "SEL"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.whitespace.render]
newline = "all"

[editor.whitespace.characters]
# newline = "␤"
newline = "·"
tab = "→"
space = "·"
tabpad = "·"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[keys.insert]
j = { k = "normal_mode" }

[keys.normal]
tab = ":buffer-next"
S-tab = ":buffer-previous"

f = "goto_word"

x = "select_line_below"
X = "select_line_above"

L = ":buffer-next"
H = ":buffer-previous"

C-r = ":toggle soft-wrap.enable"
C-h = ":toggle lsp.display-inlay-hints"
C-l = ":toggle cursorcolumn"
C-n = ":new"
C-i = ":character-info"
A-w = ":buffer-close-others"
D = ["extend_to_line_end", "delete_selection"]
ret = ["move_line_down", "goto_first_nonwhitespace"]
"$" = "goto_line_end"
"0" = "goto_first_nonwhitespace"

[keys.normal." "]
F = "file_picker_in_current_buffer_directory"

[keys.normal.","]
w = ":write-all"
f = ":format"
q = ":quit"
Q = ":quit!"
c = ":buffer-close"
C = ":buffer-close!"
o = ":buffer-close-others"
O = ":buffer-close-others!"
x = ":write-quit-all"
"," = "keep_primary_selection"

[keys.select]
u = "switch_to_lowercase"
U = "switch_to_uppercase"
