[language-server.ruff]
command = "ruff-lsp"

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.gopls.config]
buildFlags = ["-tags", "mage,integration"]
gofumpt = true
semanticTokens = true
usePlaceholders = true
experimentalPostfixCompletions = true
staticcheck = true
vulncheck = "Imports"
templateExtensions = ["tmpl", "gohtml"]

[language-server.gopls.config.completion]
usePlaceholders = true

[language-server.gopls.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

[language-server.gopls.config.analyses]
unreachable = true
# https://github.com/golang/tools/blob/master/gopls/doc/analyzers.md
unusedparams = true
nilness = true
shadow = true
unusedwrite = true
useany = true
unusedvariable = true
# fieldalignment = true

[language-server.rust-analyzer.config.inlayHints]
bindingModeHints.enable = false
closingBraceHints.minLines = 10
closureReturnTypeHints.enable = "with_block"
discriminantHints.enable = "fieldless"
lifetimeElisionHints.enable = "skip_trivial"
typeHints.hideClosureInitialization = false

[[language]]
name = "python"
language-servers = ["ruff", "pyright"]
auto-format = true

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = [
  "--parser",
  "markdown",
  "--prose-wrap",
  "always",
] }

[[language]]
name = "json"
auto-format = true
formatter = { command = "prettier", args = [
  "--parser",
  "json",
  "--tab-widt",
  "4",
] }

[[language]]
name = "vue"
file-types = ["vue"]
language-servers = ["vue"]
scope = "text.html.vue"
roots = ["package.json"]
injection-regex = "vue"

# [language.config.typescript] # this part must be hardcoded sadly, if anyone figures out how to provide a relative path let me know
# serverPath = "/home/niedzwiedz/Pieprzyk/prometeusz/prometeusz-front/node_modules/typescript/lib/tsserverlibrary.js"

[language-server.vue]
command = "vue-language-server"
args = ["--stdio"]

[language-server.vue.config.languageFeatures]
semanticTokens = false
references = true
definition = true
typeDefinition = true
callHierarchy = true
hover = true
rename = true
renameFileRefactoring = true
signatureHelp = true
codeAction = true
completion = { defaultTagNameCase = 'both', defaultAttrNameCase = 'kebabCase' }
schemaRequestService = true
documentHighlight = true
documentLink = true
codeLens = true
diagnostics = true

[language-server.vue.config.documentFeatures]
documentColor = false
selectionRange = true
foldingRange = true
linkedEditingRange = true
documentSymbol = true
documentFormatting = { defaultPrintWidth = 100 }


[[language]]
name = "yaml"
auto-format = true
formatter = { command = 'prettier', args = [
  "--parser",
  "yaml",
  "--prose-wrap",
  "always",
] }
